<a href="https://colab.research.google.com/github/AvadhAK/Hello-World/blob/master/REF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

!pip install numpy
import numpy as np

In [61]:
# prompt: generate random array of vectors (integer) of size m*n and print

m = 3
n = 4
l = 1
A = np.random.randint(0, 10, size=(m, n))
B = np.random.randint(0,10, size=(m,l))
print(A)



[[2 4 8 1]
 [2 1 1 3]
 [5 9 0 8]]


In [7]:
print(B)

[[5]
 [7]
 [9]]


In [59]:
A = np.array([[2.0, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

B = np.array([[8],
              [-11],
              [-3]])


In [52]:
A[1, :] + A[0,:]*3/2

array([0. , 0.5, 0.5])

In [22]:
A.shape[0]

3

In [43]:
# prompt: write a function to add first row to second row in A matrix

def add_two_rows(A,r1,r2,s):
  A[r2, :] = A[r2, :] + A[r1, :] * s
  return A


In [62]:
for i in range(A.shape[1]):
  for j in range(A.shape[0]-1):
      A = add_two_rows(A,i,j+1,-A[j+1][i]/A[i][i]) #A,0,2,-(-2)/
print(A)

<ipython-input-62-3158ac1caf4c>:3: RuntimeWarning: divide by zero encountered in long_scalars
  A = add_two_rows(A,i,j+1,-A[j+1][i]/A[i][i]) #A,0,2,-(-2)/
<ipython-input-43-4937dc5c2b57>:4: RuntimeWarning: invalid value encountered in multiply
  A[r2, :] = A[r2, :] + A[r1, :] * s


IndexError: ignored

In [25]:
for i in range(A.shape[1]):
  for j in range(A.shape[0]):
      A = add_two_rows(A,j,j+1)
      print(A[j,:])

[ 2  1 -1]
[-3 -1  2]
[-2  1  2]
[ 2  1 -1]
[-3 -1  2]
[-2  1  2]
[ 2  1 -1]
[-3 -1  2]
[-2  1  2]
