<a href="https://colab.research.google.com/github/AvadhAK/Hello-World/blob/master/REF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [36]:
# prompt: generate random array of vectors (integer) of size m*n and print

m = 3
n = 4
l = 1
A = np.random.randint(0, 10.0, size=(m, n))
B = np.random.randint(0,10.0, size=(m,l))
print(A)



[[3 3 8 9]
 [2 5 9 1]
 [1 8 7 9]]


In [37]:
print(B)

[[9]
 [6]
 [4]]


In [28]:
A = np.array([[2.0, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

B = np.array([[8],
              [-11],
              [-3]])


In [9]:
A[1, :] + A[0,:]*3/2

array([14.5, 10.5,  9. , 10.5])

In [13]:
A.shape[0]

3

In [14]:
def add_two_rows(A,r1,r2,s):
  A[r2, :] = A[r2, :] + A[r1, :] * s
  return A


In [ ]:
def swap_two_rows(A,r1,r2,s):
  Temp[]
  A[r2, :] = A[r1, :]
  return A


In [38]:
def REF(A):
  for i in range(A.shape[1]):
    for j in range(i, A.shape[0]-1):
      A = add_two_rows(A,i,j+1,-A[j+1][i]/A[i][i]) #A,0,2,-(-2)/
  print(A)
  return A

In [39]:
C=REF(A)

[[ 3  3  8  9]
 [ 0  3  3 -5]
 [ 0  0 -3 17]]


In [ ]:
for i in range(A.shape[1]):
  for j in range(A.shape[0]):
      A = add_two_rows(A,j,j+1)
      print(A[j,:])

[ 2  1 -1]
[-3 -1  2]
[-2  1  2]
[ 2  1 -1]
[-3 -1  2]
[-2  1  2]
[ 2  1 -1]
[-3 -1  2]
[-2  1  2]


In [43]:
def ref(matrix):
    m = matrix.astype(float)
    rows, cols = m.shape
    lead = 0

    for r in range(rows):
        if lead >= cols:
            return m
        i = r
        while m[i, lead] == 0:
            i += 1
            if i == rows:
                i = r
                lead += 1
                if cols == lead:
                    return m
        m[[i, r]] = m[[r, i]]
        lv = m[r, lead]
        m[r] = m[r] / lv
        for i in range(rows):
            if i != r:
                lv = m[i, lead]
                m[i] -= lv * m[r]
        lead += 1

    return m

# Example matrix
matrix = np.array([
    [3.0, 3, 8, 9],
    [2, 5, 9, 1],
    [1, 8, 7, 9]
])

result = ref(matrix)
print("Row Echelon Form:")
print(result)


Row Echelon Form:
[[ 1.          0.          0.         10.71052632]
 [ 0.          1.          0.          3.44736842]
 [-0.         -0.          1.         -4.18421053]]
