<a href="https://colab.research.google.com/github/AvadhAK/Hello-World/blob/master/REF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [45]:
# prompt: generate random array of vectors (integer) of size m*n and print

m = 3
n = 4
l = 1
A = np.random.randint(0, 10.0, size=(m, n))
B = np.random.randint(0,10.0, size=(m,l))
print(A)



[[6 5 1 3]
 [2 9 3 5]
 [8 7 1 6]]


In [37]:
print(B)

[[9]
 [6]
 [4]]


In [251]:
A = np.array([[2, 3, 4, 5, 6,7, 8],
              [4, 2, 5, 6, 44, 32, 2],
              [-1, 2, 2, 3,4,23, 22],
              [-10, 22, 21, 34,42,24, 28],
              [-11, 23, 25, 32,47,27, 29]])

B = np.array([[8],
              [-11],
              [-3],
              [5],
              [7]])
A = np.hstack((A,B))

print(A)

[[  2   3   4   5   6   7   8   8]
 [  4   2   5   6  44  32   2 -11]
 [ -1   2   2   3   4  23  22  -3]
 [-10  22  21  34  42  24  28   5]
 [-11  23  25  32  47  27  29   7]]


In [9]:
A[1, :] + A[0,:]*3/2

array([14.5, 10.5,  9. , 10.5])

In [13]:
A.shape[0]

3

In [135]:
def add_two_rows(A,r1,r2,s):
  A[r2, :] = A[r2, :] + A[r1, :] * s
  print("Adding")
  return A


In [147]:
def swap_two_rows(A,r1,r2):

  A[[r2, r1]] = A[[r1, r2]]
  print("Swapping")
  return A


In [237]:
def REF(A):
  for i in range(A.shape[1]):
    for j in range(i, A.shape[0]-1):
      # print("Cell Element: ", A[j][i])
      if A[j][i] == 0:
        l = j+1;
        while l<A.shape[0]:
          if A[l][i] != 0:
            A = swap_two_rows(A, j, l)
            j=j-1;
            l=A.shape[0];
            break;
          l+=1;
          # print("L iteration:", l)

      A = add_two_rows(A,i,j+1,-A[j+1][i]/A[i][i]) #A,0,2,-(-2)/

  print(A)
  return A

In [252]:
def RREF(A):
  for i in range(A.shape[1]):
    if i<A.shape[0]:
      if A[i][i] == 0:
        break;
      else:
        A[i,:] = A[i,:]/A[i][i]

  print(A)
  return A

In [253]:
REF_matrix = REF(A)

Adding
Swapping
Adding
Swapping
Adding
Swapping
Adding
Adding
Swapping
Adding
Swapping
Adding
Adding
Swapping
Adding
Adding
[[   2    3    4    5    6    7    8    8]
 [   0    3    4    5    7   26   26    1]
 [   0    0   -5   -6  -11 -273 -265   38]
 [   0    0    0    7    3  175  172  -28]
 [   0    0    0    0   36  -57  -86   -9]]


In [254]:
RREF_matrix = RREF(A)

[[ 1  1  2  2  3  3  4  4]
 [ 0  1  1  1  2  8  8  0]
 [ 0  0  1  1  2 54 53 -7]
 [ 0  0  0  1  0 25 24 -4]
 [ 0  0  0  0  1 -1 -2  0]]


In [255]:
def pivot_and_nonpivot_columns(A):
  non_pivot_column = [] ;
  pivot_column = [] ;
  rows = A.shape[0]
  for i in range(A.shape[1]):
    if i<rows and A[i][i] == 1:
      pivot_column.append(i);
    else:
      non_pivot_column.append(i);

  return pivot_column, non_pivot_column;



In [256]:
pivot_column, non_pivot_column = pivot_and_nonpivot_columns(A)
print("Pivot columns: ", pivot_column, " and Non Pivot columns: ", non_pivot_column);

Pivot columns:  [0, 1, 2, 3, 4]  and Non Pivot columns:  [5, 6, 7]


In [257]:
def particular_sol(A):
  b_matrix = A[:, -1]
  Col = A.shape[1]
  particular_sol = [0] * Col
  for i, col in enumerate(pivot_column):
      particular_sol[col] = b_matrix[i]

  return particular_sol


In [258]:
p_sol= particular_sol(A)
print("Particular Solution for matrix A: ", p_sol)

Particular Solution for matrix A:  [4, 0, -7, -4, 0, 0, 0, 0]
